### ISSUE TITLE
希望能支持docker部署同步服务

### ISSUE THREAD

**Issue by kokojacket** [fishjar/kiss-worker#1]
希望能支持docker部署该功能
或者，webdav?

**Comment by fishjar** [comment]
目前是用 Cloudflare 的免费服务，门槛应该是最低的。
如果增加docker，需要有服务器资源，还需要一些docker相关的知识才能部署。

并且不知现在使用数据同步功能的需求有多大。
后续需求的多，可以考虑增加docker的方式。

**Comment by fishjar** [comment]
新版已支持docker部署，也支持webdav了
